// Turkish translations
export const tr = {
  home: {
    scanQr: 'QR Tara',
    playGames: 'Oyunları Oyna',
    missions: 'Görevler',
    rewards: 'Ödüller',
    welcomeBack: 'Hoşgeldiniz,',
    streak: 'gün serisi!',
    currentBalance: 'Mevcut Bakiye',
    redeem: 'Kullan',
    quickActions: 'Hızlı İşlemler',
    dailyMissions: 'Günlük Görevler',
    completed: 'tamamlandı',
    featuredRewards: 'Öne Çıkan Ödüller',
    shopAll: 'Tümünü Gör',
    seeAll: 'Tümünü Gör',
    rank: 'Sıra',
    achievements: 'Başarılar',
    dayStreak: 'Gün Serisi',
  },
  shop: {
    title: 'Ödüller Dükkanı',
    searchRewards: 'Ödülleri ara...',
    limitedTime: 'Sınırlı Zaman',
    allRewards: 'Tüm Ödüller',
    limited: 'Sınırlı',
    confirmRedemption: 'Kullanımı Onayla',
    cost: 'Maliyet',
    redeem: 'Kullan',
    needMore: 'Daha Gerek',
    noRewardsFound: 'Ödül bulunamadı',
    all: 'Tümü',
    coffee: 'Kahve',
    pastries: 'Pastane',
    food: 'Yemek',
    drinks: 'İçecekler',
    cancel: 'İptal Et',
    notEnoughPoints: 'Bu ödül için yeterli puanınız yok.',
    pointsRequired: 'Gereken Puanlar',
    featured: 'Öne Çıkan Ödüller',
    onlyLeft: 'Sadece kaldı!',
  },
  missions: {
    title: 'Görevler',
    daily: 'Günlük',
    weekly: 'Haftalık',
    monthly: 'Aylık',
    completed: 'tamamlandı',
    viewAll: 'Tümünü Gör',
    claimReward: 'Ödülü Al',
    complete: 'Tamamla',
    progress: 'İlerleme',
    ptsEarned: 'puanlar kazanıldı',
    dailyReset: 'Günlük görevler gece yarısında sıfırlanır.',
    weeklyReset: 'Haftalık görevler her Pazartesi sıfırlanır.',
    allComplete: 'Tümü',
    allCompleteMsg: 'tamamlandı! Harika!',
  },
  inventory: {
    title: 'Envanterim',
    allItems: 'Tüm Öğeler',
    coupons: 'Kuponlar',
    tickets: 'Biletler',
    rewards: 'Ödüller',
    empty: 'Envanteriniz boş',
  },
  profile: {
    title: 'Profil',
    totalPoints: 'Toplam Puanlar',
    currentLevel: 'Mevcut Seviye',
    champion: 'Şampiyon',
    achievements: 'Başarılar',
    dayStreak: 'Gün Serisi',
    availablePoints: 'Mevcut Puanlar',
    redeem: 'Kullan',
    recentAchievements: 'Son Başarılar',
    viewMissions: 'Görevleri Gör',
    viewAchievements: 'Başarıları Gör',
    accountSettings: 'Hesap Ayarları',
    seeAll: 'Tümünü Gör',
    myInventory: 'Envanterim',
    activitySummary: 'Aktivite Özeti',
    qrScansThisMonth: 'Bu Ay QR Taramaları',
    gamesPlayed: 'Oynanan Oyunlar',
    rewardsRedeemed: 'Kullanılan Ödüller',
    missionsCompleted: 'Tamamlanan Görevler',
    expired: 'Süresi Doldu',
    expires: 'Süresi Doluyor:',
    logout: 'Çıkış Yap',
  },
  qr: {
    title: 'QR Kodu Tara',
    scanQr: 'QR Kodunu Tarayın',
    enterCode: 'Kodu Manuel Olarak Girin',
    placeholder: 'örn. STORE42-BONUS',
    submit: 'Gönder',
    success: 'Başarılı!',
    error: 'Hata',
  },
  games: {
    title: 'Oyunlar',
    spinWheel: 'Tekerleği Çevir',
    memory: 'Hafıza Oyunu',
    quiz: 'Quiz',
    catchGame: 'Yakalama Oyunu',
    flappyBird: 'Flappy Kuş',
    snake: 'Yılan',
    tapRhythm: 'Ritim Dokunuşu',
    colorMatch: 'Renk Eşleştirme',
    dailyChallenge: 'Günlük Zorluk',
    playGames: 'Oyunlar Oyna',
    play: 'Oyna',
    points: 'Puanlar',
    score: 'Skor',
    playAgain: 'Tekrar Oyna',
    startGame: 'Oyunu Başlat',
    spinToWin: 'Dönüp Kazanın',
    catchGifts: 'Hediyeleri Yakalayın',
    matchPairs: 'Çiftleri Eşleştirin',
    answer5Questions: '5 Soruyu Cevaplayın',
    tapToFly: 'Uçmak için Dokun',
    useArrowKeys: 'Ok Tuşlarını Kullanın',
    tapWhenHits: 'Çizgiye Çarptığında Dokun',
    tenLevelColors: '10 Seviye Renk Eşleştirme',
    earnMaxPoints: 'Maksimum ödülleri kazanmak için günlük oynayın!',
  },
  settings: {
    title: 'Ayarlar',
    account: 'Hesap',
    notifications: 'Bildirimler',
    sound: 'Ses',
    theme: 'Tema',
    language: 'Dil',
    logout: 'Çıkış Yap',
    deleteAccount: 'Hesabı Sil',
    appearance: 'Görünüm',
    languageRegion: 'Dil & Bölge',
    light: 'Açık',
    dark: 'Koyu',
    pushNotifications: 'Anında Bildirimler',
    emailNotifications: 'E-posta Bildirimleri',
    activityAlerts: 'Aktivite Uyarıları',
    soundEffects: 'Ses Efektleri',
    editProfile: 'Profili Düzenle',
    privacySecurity: 'Gizlilik & Güvenlik',
    changePassword: 'Şifreyi Değiştir',
    frontendDemo: 'Ön Yüz Demosu',
  },
  achievements: {
    title: 'Başarılar',
    common: 'Yaygın',
    rare: 'Nadir',
    epic: 'Epik',
    legendary: 'Efsanevi',
    locked: 'Kilitli',
    unlocked: 'Kilitli Açıldı',
    earned: 'Kazanıldı',
  },
  leaderboard: {
    title: 'Lider Tablosu',
    allTime: 'Tüm Zaman',
    monthly: 'Aylık',
    weekly: 'Haftalık',
    daily: 'Günlük',
    rank: 'Sıra',
    points: 'Puanlar',
  },
  notifications: {
    title: 'Bildirimler',
    empty: 'Bildirim yok',
    markAllAsRead: 'Tümünü Okundu Olarak İşaretle',
    all: 'Tüm',
    unread: 'Okunmamış',
    reward: 'Ödül',
    achievement: 'Başarı',
    points: 'Puanlar',
    event: 'Etkinlik',
  },
  common: {
    loading: 'Yükleniyor...',
    error: 'Hata',
    success: 'Başarılı',
    cancel: 'İptal Et',
    confirm: 'Onayla',
    delete: 'Sil',
    edit: 'Düzenle',
    save: 'Kaydet',
    back: 'Geri',
    next: 'İleri',
    close: 'Kapat',
    search: 'Ara',
    filter: 'Filtre',
    sort: 'Sırala',
    noData: 'Veri yok',
    tryAgain: 'Tekrar Dene',
  },
  admin: {
    dashboard: 'Yönetici Panosu',
    users: 'Kullanıcılar',
    rewards: 'Ödüller',
    events: 'Etkinlikler',
    games: 'Oyunlar',
    qr: 'QR Kodları',
    settings: 'Ayarlar',
    analytics: 'Analitikler',
    notifications: 'Bildirimler',
  },
};
