// Turkish translations - Comprehensive
export const tr = {
  // Landing Page
  landing: {
    badge: 'Ödül Programına Hoşgeldiniz!',
    heroTitle: 'Alışveriş Yaparken Ödül Kazanın',
    heroDescription: 'Binlerce mutlu müşteri ile katılın, puan kazanın, özel ödüller almaya başlayın ve gamifikasyonlu sadakat platformumuzla eğlenin.',
    getStarted: 'Başlayın',
    learnMore: 'Daha Fazla Bilgi',
    activeUsers: 'Aktif Kullanıcılar',
    pointsEarned: 'Kazanılan Puanlar',
    rewardsGiven: 'Verilen Ödüller',
    whyLoveUs: 'Neden Bizi Seveceksiniz',
    everything: 'Ödüllerinizi maksimize etmek ve alışveriş deneyiminden keyif almak için ihtiyacınız olan her şey.',
    howItWorks: 'Nasıl Çalışır',
    readyToStart: 'Başlamaya Hazır mısınız?',
    readyToStartDesc: 'Sadakat programımıza katılın ve bugün ödül toplamaya başlayın.',
    joinNow: 'Şimdi Katıl',
    features: {
      instantRewards: 'Anında Ödüller',
      instantRewardsDesc: 'Her etkileşimde puan kazanın',
      funGamification: 'Eğlenceli Oyunlaştırma',
      funGamificationDesc: 'Oyunlar oynayın ve bonuslar için görevleri tamamlayın',
      exclusiveRewards: 'Özel Ödüller',
      exclusiveRewardsDesc: 'Puanlarınızı harika ödüller için kullanın',
      dailyMissions: 'Günlük Görevler',
      dailyMissionsDesc: 'Günlük zorlukları tamamlayın ve seriler kazanın',
      leaderboards: 'Lider Tabloları',
      leaderboardsDesc: 'Diğerleriyle yarışın ve sıralamayı tırmanın',
      socialRewards: 'Sosyal Ödüller',
      socialRewardsDesc: 'Arkadaşlarla paylaşarak bonus puan kazanın',
    },
    steps: {
      step1: 'Kaydolun',
      step1Desc: 'Hesabınızı saniyeler içinde oluşturun',
      step2: 'Alışveriş Yapın',
      step2Desc: 'Her alışverişte puan alın',
      step3: 'Oyunlar Oynayın',
      step3Desc: 'Eğlenin ve bonuslar kazanın',
      step4: 'Kullanın',
      step4Desc: 'Puanlarınızı ödüller için takas edin',
    },
  },

  // Auth Pages
  auth: {
    login: 'Giriş Yap',
    register: 'Kayıt Ol',
    email: 'E-posta',
    password: 'Şifre',
    confirmPassword: 'Şifreyi Onayla',
    username: 'Kullanıcı Adı',
    forgotPassword: 'Şifremi Unuttum',
    rememberMe: 'Beni Hatırla',
    signIn: 'Giriş Yap',
    signUp: 'Kayıt Ol',
    dontHaveAccount: 'Hesabınız yok mu?',
    alreadyHaveAccount: 'Zaten bir hesabınız var mı?',
    createAccount: 'Hesap Oluştur',
    invalidEmail: 'Geçersiz e-posta',
    passwordMismatch: 'Şifreler eşleşmiyor',
    passwordTooShort: 'Şifre çok kısa',
    welcomeBack: 'Hoşgeldiniz!',
    loginSuccess: 'Başarıyla giriş yapıldı',
    registerSuccess: 'Hesap başarıyla oluşturuldu',
    loginFailed: 'Giriş başarısız',
    registerFailed: 'Kayıt başarısız',
  },

  // Home Page
  home: {
    scanQr: 'QR Tara',
    playGames: 'Oyunları Oyna',
    missions: 'Görevler',
    rewards: 'Ödüller',
    welcomeBack: 'Hoşgeldiniz,',
    streak: 'gün serisi!',
    currentBalance: 'Mevcut Bakiye',
    redeem: 'Kullan',
    quickActions: 'Hızlı İşlemler',
    dailyMissions: 'Günlük Görevler',
    completed: 'tamamlandı',
    featuredRewards: 'Öne Çıkan Ödüller',
    shopAll: 'Tümünü Gör',
    seeAll: 'Tümünü Gör',
    rank: 'Sıra',
    achievements: 'Başarılar',
    dayStreak: 'Gün Serisi',
  },

  // Shop/Rewards
  shop: {
    title: 'Ödüller Dükkanı',
    searchRewards: 'Ödülleri ara...',
    limitedTime: 'Sınırlı Zaman',
    allRewards: 'Tüm Ödüller',
    limited: 'Sınırlı',
    confirmRedemption: 'Kullanımı Onayla',
    cost: 'Maliyet',
    redeem: 'Kullan',
    needMore: 'Daha Gerek',
    noRewardsFound: 'Ödül bulunamadı',
    all: 'Tümü',
    coffee: 'Kahve',
    pastries: 'Pastane',
    food: 'Yemek',
    drinks: 'İçecekler',
    cancel: 'İptal Et',
    notEnoughPoints: 'Bu ödül için yeterli puanınız yok.',
    pointsRequired: 'Gereken Puanlar',
    featured: 'Öne Çıkan Ödüller',
    onlyLeft: 'Sadece kaldı!',
    redeemSuccess: 'Ödül başarıyla kullanıldı',
    confirmRedeem: 'Bu ödülü kullanmak istediğinizden emin misiniz?',
    category: 'Kategori',
    price: 'Fiyat',
    addToCart: 'Sepete Ekle',
    quantity: 'Miktar',
    stock: 'Stok',
  },

  // Missions
  missions: {
    title: 'Görevler',
    daily: 'Günlük',
    weekly: 'Haftalık',
    monthly: 'Aylık',
    completed: 'tamamlandı',
    viewAll: 'Tümünü Gör',
    claimReward: 'Ödülü Al',
    complete: 'Tamamla',
    progress: 'İlerleme',
    ptsEarned: 'puanlar kazanıldı',
    dailyReset: 'Günlük görevler gece yarısında sıfırlanır.',
    weeklyReset: 'Haftalık görevler her Pazartesi sıfırlanır.',
    monthlyReset: 'Aylık görevler ayın başında sıfırlanır.',
    allComplete: 'Tümü',
    allCompleteMsg: 'tamamlandı! Harika!',
    noMissions: 'Şu anda görev yok',
    rewardClaimed: 'Ödül başarıyla alındı',
    claimRewardConfirm: 'Ödülü almak istiyor musunuz?',
  },

  // Inventory
  inventory: {
    title: 'Envanterim',
    allItems: 'Tüm Öğeler',
    coupons: 'Kuponlar',
    tickets: 'Biletler',
    rewards: 'Ödüller',
    empty: 'Envanteriniz boş',
    use: 'Kullan',
    used: 'Kullanıldı',
    expired: 'Süresi Doldu',
    expiresOn: 'Süresi Doluyor:',
    viewDetails: 'Detayları Gör',
    itemUsed: 'Öğe başarıyla kullanıldı',
  },

  // Profile
  profile: {
    title: 'Profil',
    totalPoints: 'Toplam Puanlar',
    currentLevel: 'Mevcut Seviye',
    champion: 'Şampiyon',
    achievements: 'Başarılar',
    dayStreak: 'Gün Serisi',
    availablePoints: 'Mevcut Puanlar',
    redeem: 'Kullan',
    recentAchievements: 'Son Başarılar',
    viewMissions: 'Görevleri Gör',
    viewAchievements: 'Başarıları Gör',
    accountSettings: 'Hesap Ayarları',
    seeAll: 'Tümünü Gör',
    myInventory: 'Envanterim',
    activitySummary: 'Aktivite Özeti',
    qrScansThisMonth: 'Bu Ay QR Taramaları',
    gamesPlayed: 'Oynanan Oyunlar',
    rewardsRedeemed: 'Kullanılan Ödüller',
    missionsCompleted: 'Tamamlanan Görevler',
    editProfile: 'Profili Düzenle',
    changeAvatar: 'Avatar Değiştir',
    joinDate: 'Katılma Tarihi',
    memberSince: 'Üye Olması:',
    statistics: 'İstatistikler',
    personalInfo: 'Kişisel Bilgiler',
    preferences: 'Tercihler',
  },

  // QR Scanner
  qr: {
    title: 'QR Kodu Tara',
    scanQr: 'QR Kodunu Tarayın',
    enterCode: 'Kodu Manuel Olarak Girin',
    placeholder: 'örn. STORE42-BONUS',
    submit: 'Gönder',
    success: 'Başarılı!',
    successMsg: 'QR kod başarıyla tarandı',
    error: 'Hata',
    invalidCode: 'Geçersiz kod',
    codeNotFound: 'Kod bulunamadı',
    pointsEarned: 'Puanlar kazanıldı',
    camera: 'Kamera',
    manual: 'Manuel',
    cameraPermission: 'Lütfen kamera izni verin',
  },

  // Games
  games: {
    title: 'Oyunlar',
    spinWheel: 'Tekerleği Çevir',
    memory: 'Hafıza Oyunu',
    quiz: 'Quiz',
    catchGame: 'Yakalama Oyunu',
    flappyBird: 'Flappy Kuş',
    snake: 'Yılan',
    tapRhythm: 'Ritim Dokunuşu',
    colorMatch: 'Renk Eşleştirme',
    dailyChallenge: 'Günlük Zorluk',
    playGames: 'Oyunlar Oyna',
    play: 'Oyna',
    points: 'Puanlar',
    score: 'Skor',
    playAgain: 'Tekrar Oyna',
    startGame: 'Oyunu Başlat',
    spinToWin: 'Dönüp Kazanın',
    catchGifts: 'Hediyeleri Yakalayın',
    matchPairs: 'Çiftleri Eşleştirin',
    answer5Questions: '5 Soruyu Cevaplayın',
    tapToFly: 'Uçmak için Dokun',
    useArrowKeys: 'Ok Tuşlarını Kullanın',
    tapWhenHits: 'Çizgiye Çarptığında Dokun',
    tenLevelColors: '10 Seviye Renk Eşleştirme',
    earnMaxPoints: 'Maksimum ödülleri kazanmak için günlük oynayın!',
    gameOver: 'Oyun Bitti',
    finalScore: 'Son Puan',
    alreadyPlayed: 'Bugün bu oyunu zaten oynadınız',
    playTomorrow: 'Yarın tekrar oynayabilirsiniz',
    difficulty: 'Zorluk',
    easy: 'Kolay',
    medium: 'Orta',
    hard: 'Zor',
  },

  // Settings
  settings: {
    title: 'Ayarlar',
    account: 'Hesap',
    notifications: 'Bildirimler',
    sound: 'Ses',
    theme: 'Tema',
    language: 'Dil',
    logout: 'Çıkış Yap',
    deleteAccount: 'Hesabı Sil',
    appearance: 'Görünüm',
    languageRegion: 'Dil & Bölge',
    light: 'Açık',
    dark: 'Koyu',
    auto: 'Otomatik',
    pushNotifications: 'Anında Bildirimler',
    emailNotifications: 'E-posta Bildirimleri',
    activityAlerts: 'Aktivite Uyarıları',
    soundEffects: 'Ses Efektleri',
    editProfile: 'Profili Düzenle',
    privacySecurity: 'Gizlilik & Güvenlik',
    changePassword: 'Şifreyi Değiştir',
    frontendDemo: 'Ön Yüz Demosu',
    twoFactor: 'İki Faktörlü Kimlik Doğrulama',
    dataBackup: 'Veri Yedeklemesi',
    helpSupport: 'Yardım & Destek',
    aboutApp: 'Uygulama Hakkında',
    termsOfService: 'Hizmet Şartları',
    privacyPolicy: 'Gizlilik Politikası',
    contactUs: 'Bizimle İletişime Geçin',
    version: 'Sürüm',
    savedSuccessfully: 'Başarıyla kaydedildi',
    deleteAccountWarning: 'Hesabınız kalıcı olarak silinecektir. Bu işlem geri alınamaz.',
    confirmDelete: 'Hesabı sil',
    cancel: 'İptal Et',
  },

  // Achievements
  achievements: {
    title: 'Başarılar',
    common: 'Yaygın',
    rare: 'Nadir',
    epic: 'Epik',
    legendary: 'Efsanevi',
    locked: 'Kilitli',
    unlocked: 'Kilitli Açıldı',
    earned: 'Kazanıldı',
    earnedOn: 'Kazanıldı:',
    earnCondition: 'Koşul:',
    totalEarned: 'Toplam Kazanılan',
    progress: 'İlerleme',
    unlockedRecently: 'Son Zamanlarda Açılanlar',
    allAchievements: 'Tüm Başarılar',
  },

  // Leaderboard
  leaderboard: {
    title: 'Lider Tablosu',
    allTime: 'Tüm Zaman',
    monthly: 'Aylık',
    weekly: 'Haftalık',
    daily: 'Günlük',
    rank: 'Sıra',
    points: 'Puanlar',
    username: 'Kullanıcı Adı',
    level: 'Seviye',
    yourRank: 'Sizin Sıranız',
    topPlayers: 'En İyi Oyuncular',
    reachTop: 'En iyi 10'a ulaşmak için daha fazla puan kazanın!',
  },

  // Notifications
  notifications: {
    title: 'Bildirimler',
    empty: 'Bildirim yok',
    markAllAsRead: 'Tümünü Okundu Olarak İşaretle',
    all: 'Tüm',
    unread: 'Okunmamış',
    reward: 'Ödül',
    achievement: 'Başarı',
    points: 'Puanlar',
    event: 'Etkinlik',
    system: 'Sistem',
    noUnreadNotifications: 'Okunmamış bildiriminiz yok',
    allCaughtUp: 'Tüm güncel!',
    deleteNotification: 'Bildirimi sil',
    deleted: 'Bildirim silindi',
  },

  // Progress/Levels
  progress: {
    title: 'İlerleme Yolu',
    currentLevel: 'Mevcut Seviye',
    nextLevel: 'Sonraki Seviye',
    xpNeeded: 'İhtiyaç duyulan XP',
    totalXp: 'Toplam XP',
    levelUp: 'Seviye Atla!',
    rewards: 'Seviyeleme Ödülleri',
    milestone: 'Dönüm Noktası',
    locked: 'Kilitli',
    unlocked: 'Açıldı',
  },

  // History
  history: {
    title: 'Geçmiş',
    pointsEarned: 'Kazanılan Puanlar',
    pointsSpent: 'Harcanan Puanlar',
    recentActivity: 'Son Aktivite',
    noHistory: 'Geçmiş yok',
    filterBy: 'Filtrele',
    dateRange: 'Tarih Aralığı',
    from: 'Başlangıç',
    to: 'Bitiş',
    activity: 'Aktivite',
    date: 'Tarih',
    source: 'Kaynak',
  },

  // Support/Help
  support: {
    title: 'Destek',
    help: 'Yardım',
    contact: 'İletişim',
    faq: 'Sık Sorulan Sorular',
    reportIssue: 'Sorunu Bildir',
    feedback: 'Geri Bildirim',
    email: 'E-posta',
    phone: 'Telefon',
    message: 'Mesaj',
    subject: 'Konu',
    send: 'Gönder',
    sentSuccessfully: 'Başarıyla gönderildi',
    ticketNumber: 'Bilet Numarası',
    expectedResponse: 'Beklenen Yanıt Süresi: 24 saat',
    commonIssues: 'Yaygın Sorunlar',
    howToEarn: 'Puan Nasıl Kazanırım?',
    howToRedeem: 'Ödülü Nasıl Kullanırım?',
    pointsExpired: 'Puanlarım Neden Doldu?',
    cannotScan: 'QR Kodu Tarayamıyorum',
  },

  // Seasonal Events
  events: {
    title: 'Mevsimsel Etkinlikler',
    active: 'Aktif Etkinlikler',
    upcoming: 'Yaklaşan Etkinlikler',
    ended: 'Biten Etkinlikler',
    participate: 'Katıl',
    participating: 'Katılıyor',
    joined: 'Katıldınız',
    eventEnds: 'Etkinlik Bitiyor:',
    rewards: 'Etkinlik Ödülleri',
    leaderboard: 'Etkinlik Lider Tablosu',
    noActiveEvents: 'Şu anda aktif etkinlik yok',
    standBy: 'Yaklaşan etkinlikler için bizi takip edin!',
  },

  // Stats/Analytics
  stats: {
    title: 'İstatistikler',
    userStats: 'Kullanıcı İstatistikleri',
    thisMonth: 'Bu Ay',
    thisWeek: 'Bu Hafta',
    today: 'Bugün',
    totalEarned: 'Toplam Kazanılan',
    totalSpent: 'Toplam Harcanan',
    availableBalance: 'Mevcut Bakiye',
    gamesPlayed: 'Oynanan Oyunlar',
    avgScore: 'Ortalama Skor',
    rewardsRedeemed: 'Kullanılan Ödüller',
    missionsCompleted: 'Tamamlanan Görevler',
    currentStreak: 'Mevcut Seri',
    longestStreak: 'En Uzun Seri',
  },

  // Admin Dashboard
  admin: {
    dashboard: 'Yönetici Panosu',
    users: 'Kullanıcılar',
    rewards: 'Ödüller',
    events: 'Etkinlikler',
    games: 'Oyunlar',
    qr: 'QR Kodları',
    settings: 'Ayarlar',
    analytics: 'Analitikler',
    notifications: 'Bildirimler',
    reports: 'Raporlar',
    manageUsers: 'Kullanıcıları Yönet',
    manageRewards: 'Ödülleri Yönet',
    manageEvents: 'Etkinlikleri Yönet',
    manageGames: 'Oyunları Yönet',
    systemHealth: 'Sistem Durumu',
    activeUsers: 'Aktif Kullanıcılar',
    totalPoints: 'Toplam Puanlar',
    totalRewards: 'Toplam Ödüller',
    totalEarnings: 'Toplam Kazançlar',
    recentActivity: 'Son Aktivite',
    topUsers: 'En İyi Kullanıcılar',
    userManagement: 'Kullanıcı Yönetimi',
    addUser: 'Kullanıcı Ekle',
    editUser: 'Kullanıcı Düzenle',
    deleteUser: 'Kullanıcı Sil',
    rewardManagement: 'Ödül Yönetimi',
    addReward: 'Ödül Ekle',
    editReward: 'Ödül Düzenle',
    deleteReward: 'Ödül Sil',
    eventManagement: 'Etkinlik Yönetimi',
    addEvent: 'Etkinlik Ekle',
    editEvent: 'Etkinlik Düzenle',
    deleteEvent: 'Etkinlik Sil',
    gameManagement: 'Oyun Yönetimi',
    addGame: 'Oyun Ekle',
    editGame: 'Oyun Düzenle',
    deleteGame: 'Oyun Sil',
    qrManagement: 'QR Kodu Yönetimi',
    generateQR: 'QR Kodu Oluştur',
    bulkGenerate: 'Toplu Oluştur',
    qrScans: 'QR Taramaları',
    systemSettings: 'Sistem Ayarları',
    generalSettings: 'Genel Ayarlar',
    pointsSettings: 'Puanlar Ayarları',
    notificationSettings: 'Bildirim Ayarları',
    analyticsReports: 'Analitik Raporları',
    userGrowth: 'Kullanıcı Büyümesi',
    pointsDistribution: 'Puanlar Dağılımı',
    rewardUsage: 'Ödül Kullanımı',
    gameStatistics: 'Oyun İstatistikleri',
    exportData: 'Verileri Dışa Aktar',
    importData: 'Verileri İçe Aktar',
    auditLogs: 'Denetim Günlükleri',
    backup: 'Yedekleme',
    restore: 'Geri Yükleme',
  },

  // Admin Users
  adminUsers: {
    title: 'Kullanıcı Yönetimi',
    totalUsers: 'Toplam Kullanıcılar',
    activeUsers: 'Aktif Kullanıcılar',
    inactiveUsers: 'İnaktif Kullanıcılar',
    bannedUsers: 'Yasaklı Kullanıcılar',
    userId: 'Kullanıcı Kimliği',
    username: 'Kullanıcı Adı',
    email: 'E-posta',
    joinDate: 'Katılma Tarihi',
    lastActive: 'Son Aktif',
    status: 'Durum',
    actions: 'İşlemler',
    ban: 'Yasakla',
    unban: 'Yasaklamayı Kaldır',
    resetPassword: 'Şifreyi Sıfırla',
    givePoints: 'Puan Ver',
    removePoints: 'Puan Kaldır',
    viewDetails: 'Detayları Gör',
    noUsers: 'Kullanıcı bulunamadı',
    search: 'Ara',
    filter: 'Filtre',
  },

  // Admin Rewards
  adminRewards: {
    title: 'Ödül Yönetimi',
    totalRewards: 'Toplam Ödüller',
    activeRewards: 'Aktif Ödüller',
    expiredRewards: 'Süresi Dolmuş Ödüller',
    rewardId: 'Ödül Kimliği',
    rewardName: 'Ödül Adı',
    pointsCost: 'Puan Maliyeti',
    category: 'Kategori',
    quantity: 'Miktar',
    stock: 'Stok',
    status: 'Durum',
    actions: 'İşlemler',
    edit: 'Düzenle',
    delete: 'Sil',
    deactivate: 'Devre Dışı Bırak',
    activate: 'Etkinleştir',
    addReward: 'Ödül Ekle',
    rewardForm: {
      name: 'Ödül Adı',
      description: 'Açıklama',
      pointsCost: 'Puan Maliyeti',
      category: 'Kategori',
      quantity: 'Miktar',
      image: 'Resim',
      expiryDate: 'Son Kullanma Tarihi',
      featured: 'Öne Çıkan',
      limited: 'Sınırlı',
    },
  },

  // Admin Events
  adminEvents: {
    title: 'Etkinlik Yönetimi',
    totalEvents: 'Toplam Etkinlikler',
    activeEvents: 'Aktif Etkinlikler',
    upcomingEvents: 'Yaklaşan Etkinlikler',
    endedEvents: 'Biten Etkinlikler',
    eventName: 'Etkinlik Adı',
    startDate: 'Başlama Tarihi',
    endDate: 'Bitiş Tarihi',
    participants: 'Katılımcılar',
    status: 'Durum',
    actions: 'İşlemler',
    edit: 'Düzenle',
    delete: 'Sil',
    addEvent: 'Etkinlik Ekle',
    eventForm: {
      name: 'Etkinlik Adı',
      description: 'Açıklama',
      startDate: 'Başlama Tarihi',
      endDate: 'Bitiş Tarihi',
      image: 'Resim',
      rewards: 'Ödüller',
      maxParticipants: 'Maksimum Katılımcılar',
      featured: 'Öne Çıkan',
    },
  },

  // Admin Games
  adminGames: {
    title: 'Oyun Yönetimi',
    totalGames: 'Toplam Oyunlar',
    activeGames: 'Aktif Oyunlar',
    gameName: 'Oyun Adı',
    plays: 'Oynanmalar',
    avgScore: 'Ortalama Skor',
    status: 'Durum',
    actions: 'İşlemler',
    edit: 'Düzenle',
    delete: 'Sil',
    addGame: 'Oyun Ekle',
    gameForm: {
      name: 'Oyun Adı',
      description: 'Açıklama',
      difficulty: 'Zorluk',
      maxPoints: 'Maksimum Puanlar',
      timeLimit: 'Zaman Sınırı',
      dailyLimit: 'Günlük Sınır',
      featured: 'Öne Çıkan',
    },
  },

  // Admin QR
  adminQr: {
    title: 'QR Kodu Yönetimi',
    totalQr: 'Toplam QR Kodları',
    activeQr: 'Aktif QR Kodları',
    usedQr: 'Kullanılan QR Kodları',
    expiredQr: 'Süresi Dolmuş QR Kodları',
    code: 'Kod',
    value: 'Değer',
    used: 'Kullanılıyor',
    usedBy: 'Tarafından Kullanıldı',
    createdDate: 'Oluşturulan Tarih',
    expiryDate: 'Son Kullanma Tarihi',
    actions: 'İşlemler',
    deactivate: 'Devre Dışı Bırak',
    generateQr: 'QR Kodu Oluştur',
    bulkGenerate: 'Toplu Oluştur',
    download: 'İndir',
    generateForm: {
      quantity: 'Miktar',
      value: 'Değer',
      expiryDate: 'Son Kullanma Tarihi',
      campaign: 'Kampanya',
    },
  },

  // Admin Analytics
  adminAnalytics: {
    title: 'Analitikler',
    overview: 'Genel Bakış',
    userMetrics: 'Kullanıcı Metrikleri',
    pointsMetrics: 'Puanlar Metrikleri',
    rewardMetrics: 'Ödüller Metrikleri',
    gameMetrics: 'Oyun Metrikleri',
    totalUsers: 'Toplam Kullanıcılar',
    newUsers: 'Yeni Kullanıcılar',
    activeUsers: 'Aktif Kullanıcılar',
    totalPoints: 'Toplam Puanlar',
    pointsEarned: 'Kazanılan Puanlar',
    pointsSpent: 'Harcanan Puanlar',
    totalRewards: 'Toplam Ödüller',
    rewardsRedeemed: 'Kullanılan Ödüller',
    rewardValue: 'Ödül Değeri',
    totalGames: 'Toplam Oyunlar',
    gamePlays: 'Oyun Oynanmaları',
    avgGameScore: 'Ortalama Oyun Puanı',
    period: 'Dönem',
    selectPeriod: 'Dönem Seçin',
    today: 'Bugün',
    week: 'Bu Hafta',
    month: 'Bu Ay',
    year: 'Bu Yıl',
    custom: 'Özel',
    export: 'Dışa Aktar',
    chart: 'Grafik',
    table: 'Tablo',
  },

  // Admin Notifications
  adminNotifications: {
    title: 'Bildirim Yönetimi',
    sendNotification: 'Bildirim Gönder',
    allNotifications: 'Tüm Bildirimler',
    sentNotifications: 'Gönderilen Bildirimler',
    failedNotifications: 'Başarısız Bildirimler',
    recipientTitle: 'Bildirim Başlığı',
    recipientMessage: 'Bildirim Mesajı',
    recipientType: 'Alıcı Türü',
    allUsers: 'Tüm Kullanıcılar',
    specificUsers: 'Belirli Kullanıcılar',
    userSegment: 'Kullanıcı Segmenti',
    notificationType: 'Bildirim Türü',
    general: 'Genel',
    promotion: 'Promosyon',
    reward: 'Ödül',
    event: 'Etkinlik',
    system: 'Sistem',
    schedule: 'Zamanla',
    sendNow: 'Şimdi Gönder',
    scheduleLater: 'Daha Sonra Zamanla',
    status: 'Durum',
    sent: 'Gönderildi',
    pending: 'Beklemede',
    failed: 'Başarısız',
    deliveryStatus: 'Teslimat Durumu',
    readStatus: 'Okuma Durumu',
    readCount: 'Okuma Sayısı',
    deliveredCount: 'Teslimat Sayısı',
    failedCount: 'Başarısız Sayısı',
  },

  // Admin Settings
  adminSettings: {
    title: 'Sistem Ayarları',
    general: 'Genel',
    points: 'Puanlar',
    rewards: 'Ödüller',
    notifications: 'Bildirimler',
    security: 'Güvenlik',
    maintenance: 'Bakım',
    pointsExchangeRate: 'Puanlar Takas Oranı',
    qrRewardValue: 'QR Ödülü Değeri',
    dailyEarningLimit: 'Günlük Kazanç Sınırı',
    pointsExpirationDays: 'Puanlar Süresi Doluş Günleri',
    signupBonus: 'Kayıt Bonusu',
    dailyLoginBonus: 'Günlük Giriş Bonusu',
    featureToggle: 'Özellik Aç/Kapat',
    enableQrScanning: 'QR Taramayı Etkinleştir',
    enableGames: 'Oyunları Etkinleştir',
    enableMissions: 'Görevleri Etkinleştir',
    enableLeaderboard: 'Lider Tablosunu Etkinleştir',
    apiKeys: 'API Anahtarları',
    maintenanceMode: 'Bakım Modu',
    backupDatabase: 'Veritabanını Yedekle',
    restoreDatabase: 'Veritabanını Geri Yükle',
    saveSettings: 'Ayarları Kaydet',
    settingsSaved: 'Ayarlar başarıyla kaydedildi',
  },

  // Common
  common: {
    loading: 'Yükleniyor...',
    error: 'Hata',
    success: 'Başarılı',
    cancel: 'İptal Et',
    confirm: 'Onayla',
    delete: 'Sil',
    edit: 'Düzenle',
    save: 'Kaydet',
    back: 'Geri',
    next: 'İleri',
    close: 'Kapat',
    search: 'Ara',
    filter: 'Filtre',
    sort: 'Sırala',
    noData: 'Veri yok',
    tryAgain: 'Tekrar Dene',
    yes: 'Evet',
    no: 'Hayır',
    loading_msg: 'Lütfen bekleyin...',
    error_msg: 'Bir hata oluştu. Lütfen tekrar deneyin.',
    success_msg: 'İşlem başarılı',
    warning: 'Uyarı',
    info: 'Bilgi',
    more: 'Daha Fazla',
    less: 'Daha Az',
    all: 'Tümü',
    results: 'Sonuçlar',
    export: 'Dışa Aktar',
    import: 'İçe Aktar',
    download: 'İndir',
    upload: 'Yükle',
    refresh: 'Yenile',
    language: 'Dil',
    turkish: 'Türkçe',
    english: 'English',
    selectLanguage: 'Dil Seçin',
  },
};
