// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/neo-brutal-home/GeoShapes.tsx": () => import("../components/mockups/neo-brutal-home/GeoShapes.tsx"),
  "./components/mockups/neo-brutal-home/GridDots.tsx": () => import("../components/mockups/neo-brutal-home/GridDots.tsx"),
  "./components/mockups/neo-brutal-home/NoiseStripes.tsx": () => import("../components/mockups/neo-brutal-home/NoiseStripes.tsx")
};
